# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calcule les flux obligataires.
#'
#' \code{echeancier} est une methode permettant de calculer les flux jusqu'a maturite residuelle d'un model point ou
#' d'un ensemble de model points obligataires.
#' @name echeancier
#' @docType methods
#' @param coupon un vecteur contenant les taux de coupons de chaque obligation.
#' @param maturite un vecteur d'entiers contenant les maturites residuelles de chaque obligation.
#' @param zspread un vecteur contenant les zero-spreadsde chaque obligation.
#' @param nominal un vecteur contenant les valeurs nominales de chaque obligation.
#' @param yield un vecteur contenant la courbe de taux consideree (peut-etre vide).
#' @return Une matrice contenant :
#' \describe{
#' \item{\code{grid_flux} : }{la matrice d'ecoulement des flux. Cette matrice a autant de colonnes
#' que le max du vecteur de maturite residuelle, et autant de lignes que les vecteurs d'input
#' \code{coupon, maturite, zspread, nominal}.
#' Chaque ligne decrit les flux annuels a venir pour l'actif obligataire dont les caracteristiques sont
#' renseignees en input.}
#' }
#' @author Prim'Act
#' @export
#' @include Oblig_class.R
NULL

echeancier <- function(coupon, maturite, zspread, nominal, yield) {
    .Call('SimBEL_echeancier', PACKAGE = 'SimBEL', coupon, maturite, zspread, nominal, yield)
}

#' Calcule le taux de revalorisation cible.
#'
#' \code{calc_tx_cible_ref_marche} est une methode permettant de calculer le taux de revalorisation cible
#' en evaluant le taux de rendement des assureurs sur le marche.
#' @name calc_tx_cible_ref_marche
#' @docType methods
#' @param param_comport un objet de la classe \code{\link{ParamComport}} contenant les parametres
#'  comportementaux.
#' @param list_rd une liste contenant les rendements de reference. Le format de cette liste est :
#' \describe{
#' \item{le taux de rendement obligataire}{}
#' \item{le taux de rendement de l'indice action de reference}{}
#' \item{le taux de rendement de l'indice immobilier de reference}{}
#' \item{le taux de rendement de l'indice tresorerie de reference}{}
#' }
#' @param tx_cible_prec une valeur \code{numeric} correspondant au taux cible de la periode precedente.
#' @return La valeur du taux cible.
#' @author Prim'Act
#' @export
#' @include ParamComport-class.R
NULL

calc_tx_cible_ref_marche <- function(rdt, alloc_mar, ch_enc_mar, marge_mar, w_n, tx_cible_prec) {
    .Call('SimBEL_calc_tx_cible_ref_marche', PACKAGE = 'SimBEL', rdt, alloc_mar, ch_enc_mar, marge_mar, w_n, tx_cible_prec)
}

#' Calcule la composante rachats dynamique.
#'
#' \code{calc_rach_dyn} est une methode permettant de calculer la composante rachat dynamique
#' selon la methodologie transmise dans le ONC de l'ACPR de 2013.
#' @name calc_rach_dyn
#' @docType methods
#' @param p un objet de la classe \code{\link{ParamRachDyn}} contenant les parametres de rachats dynamiques.
#' @param tx_cible une valeur \code{numeric} correspondant au taux de revalorisation cible.
#' @param tx_serv une valeur \code{numeric} correspondant au taux de revalorisation servi.
#' @return La valeur du taux rachat.
#' @author Prim'Act
#' @include ParamRachDyn-class.R
#' @export
NULL

calc_rach_dyn <- function(vec_param, tx_cible, tx_serv) {
    .Call('SimBEL_calc_rach_dyn', PACKAGE = 'SimBEL', vec_param, tx_cible, tx_serv)
}

